import 'dotenv/config';
import http from 'http';
import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import bcrypt from 'bcryptjs';
import authRoutes from './routes/auth.js';
import issueRoutes from './routes/issues.js';
import miscRoutes from './routes/misc.js';
import { initRealtime } from './services/realtime.js';
import { seedDemoUsers } from './store.js';
const app=express();
app.use(cors({origin:process.env.CLIENT_ORIGIN||'http://localhost:5173',credentials:true}));
app.use(express.json({limit:'1mb'}));app.use((req,_res,next)=>{req.cookies=Object.fromEntries((req.headers.cookie||'').split(';').map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf('=');return [decodeURIComponent(v.slice(0,i)),decodeURIComponent(v.slice(i+1))]}));next();});app.use(morgan('dev'));
app.use('/uploads',express.static(new URL('../uploads',import.meta.url).pathname));
app.get('/api/health',(_req,res)=>res.json({ok:true,storage:'in-memory'}));
app.use('/api/auth',authRoutes);app.use('/api/issues',issueRoutes);app.use('/api',miscRoutes);
app.use((err,_req,res,_next)=>{console.error(err);res.status(err.status||500).json({error:err.message||'Server error'});});
const server=http.createServer(app);initRealtime(server);const PORT=process.env.PORT||5000;
bcrypt.hash(process.env.DEMO_PASSWORD||'password123',10).then(hash=>{seedDemoUsers(hash);server.listen(PORT,()=>console.log(`CivicForge API + WebSocket on :${PORT} (in-memory store)`));});
